# Site settings
author: Mei Zhu
title: Why am I studying Software Engineering?
header-img: img/home-bg.png
email: meidan.zhu@gmail.com
copyright_name: Mei Zhu
description: > # this means to ignore newlines until "baseurl:"
  blog #1
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  meidanzhu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
